# .github/workflows/release-slideUI.yml
name: Release-slideUI
on:
  push:
    branches: [ main ]
    paths:
      - src/pptm/slideUI.xlam
jobs:
  release:
    runs-on: windows-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: main
          tag_prefix: slideUI-v
      - run: >
          New-Item -ItemType Directory -Force -Path src\rel | Out-Null;
          Compress-Archive -Path
          src\pptm\slideUI.pptm
          -DestinationPath src\rel\slideUI.zip -Force
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          generate_release_notes: true
          files: src/rel/slideUI.zip
